### ISSUE TITLE
add Sass support for css

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#12]

**Comment by Tjoosten** [comment]
Note: Release off the port is planned tomorrow around midnight

**Comment by ghermans** [comment]
Added the "In Progress" label so we know you are working on this.

**Comment by Tjoosten** [comment]
@ghermans de scss files are up. But only needs linting and fix the throwed error from scss-lint. I'm working this right now.

**Comment by ghermans** [comment]
@Tjoosten  components are created , can you please verify if they are ok?

**Comment by ghermans** [comment]
30days since last comment, no answer from @Tjoosten , issue closed..
