### ISSUE TITLE
Add github templates

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#121]
- [x] Bug reports
- [x] Pull requests

**Comment by Tjoosten** [comment]
Can u explain more plz?

**Comment by ghermans** [comment]
@Tjoosten  Since 17 February Github supports issue & pull request templates more info can be found [here](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by ghermans** [comment]
@Tjoosten first version for the template is added, feedback is always welcome :)

**Comment by Tjoosten** [comment]
I will check it tomorrow? Or is it ASAP?

**Comment by ghermans** [comment]
tomorrow is fine
