### ISSUE TITLE
Add vagrant box

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#18]
- Homestead

**Comment by Tjoosten** [comment]
Need help with this one @ghermans

**Comment by ghermans** [comment]
What is the issue you are having with this one?

**Comment by Tjoosten** [comment]
UID issues

**Comment by ghermans** [comment]
@Tjoosten shall we have a skype or gitter chat about this? i'm using ubuntu on my desktop , just did a clean install , added my ssh keys, changed the shared folder to the project folder and did vagrant up.
![selection_0122](https://cloud.githubusercontent.com/assets/1594411/10237169/7f9f1244-68ae-11e5-875a-f74917ea77d7.png)

**Comment by Tjoosten** [comment]
@ghermans can i get a update. Because i like to close this one.
