### ISSUE TITLE
Create connection to suitecrm

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#2]
Authenticate to the CRM and import portal users to the default laravel authentication system.

**Comment by Tjoosten** [comment]
?

**Comment by ghermans** [comment]
@Tjoosten  description has been updated

**Comment by ghermans** [comment]
We should have a look at how the code from the Joomla component is calling the Suite Rest client and then recreate that in Laravel.

**Comment by ghermans** [comment]
@Tjoosten Do you have experience with implementing this one https://packagist.org/packages/fergusean/nusoap to laravel ?

**Comment by Tjoosten** [comment]
I can try

**Comment by ghermans** [comment]
@Tjoosten  do you have any idea when a first push for this will be executed?

**Comment by ghermans** [comment]
Because @Tjoosten  is not working on the project anymore, i will add curl to the portal.

**Comment by Tjoosten** [comment]
I'm still working on this but not on this moment. Busy social life these days.

**Comment by Tjoosten** [comment]
https://github.com/idevelopment/suitecrm_laravel/commit/172c5a0b76d576ec02f82bdb927bb7458b32f852

**Comment by Tjoosten** [comment]
@ghermans is this done for you. If yes this can be closed.

**Comment by ghermans** [comment]
@Tjoosten  Testing is done as spoken on skype when you pushed the commits for this.
