### ISSUE TITLE
Add multiple language support

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#28]
Users should be able to change the interface language.

**Comment by Tjoosten** [comment]
I'm writing the blade commands and middleware. Can you do the css changes later on when the scss port is up. 

SCSS port is coming tomorrow.

**Comment by ghermans** [comment]
For this enhancement css files don't need any modifications.

**Comment by Tjoosten** [comment]
Alright then. i was thinking you need to design a component for it

**Comment by Tjoosten** [comment]
What languages we support, @ghermans?

**Comment by ghermans** [comment]
by default: en/nl/fr

**Comment by Tjoosten** [comment]
Alright I'm working on the middleware

**Comment by Tjoosten** [comment]
Middleware file is up. Only it needs to be set in the Kernel.php

**Comment by ghermans** [comment]
The theme has been updated for language selection, only the links need to be added.

![selection_018](https://cloud.githubusercontent.com/assets/1594411/10272870/cb246c44-6b26-11e5-95ac-0e1b56141863.png)

**Comment by Tjoosten** [comment]
alright i will do that when i get back from colledge

**Comment by Tjoosten** [comment]
Todo list for me: 

- [ ] register language middleware into the kernel.php 
- [ ] Activate it into the controllers. 
- [ ] Double check the translation file(s).

**Comment by ghermans** [comment]
I added the middleware to the kernel this night.

**Comment by Tjoosten** [comment]
links are set
