### ISSUE TITLE
Case module: create/edit/view

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#3]
For the current moment the cases controller is just loaded with static data, this was done to create the theme for the portal.

**Comment by Tjoosten** [comment]
Can u explain?

**Comment by ghermans** [comment]
Current static data

![selection_004](https://cloud.githubusercontent.com/assets/1594411/9979978/39a5407c-5f87-11e5-8dc1-bb676b2c6555.png)

![selection_005](https://cloud.githubusercontent.com/assets/1594411/9979981/64af4498-5f87-11e5-8ae5-e96e4d3f50b4.png)

**Comment by ghermans** [comment]
@Tjoosten  sorry if it was not clear, i created the issue to remind me that this feature still has to be added to the portal.

**Comment by Tjoosten** [comment]
Alright. But maybe we need to add a discription so it is clear to contributors
