### ISSUE TITLE
Kill the styleCI errors.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#31]

**Comment by ghermans** [comment]
it looks like it does not accept the default laravel files?

**Comment by Tjoosten** [comment]
It does. I will work that out.

**Comment by Tjoosten** [comment]
StyleCI config is added now normally.

**Comment by ghermans** [comment]
It still returns the status failed 
![selection_016](https://cloud.githubusercontent.com/assets/1594411/10269391/a60b62fa-6ad6-11e5-974a-e5be38822aad.png)

**Comment by Tjoosten** [comment]
I know the config is added but i'm busy with the contribution guidelines; Will fix this at least tomorrow

**Comment by Tjoosten** [comment]
In halt. Because styleCI free plan is not for organizations. @ghermans Maybe we need search for a new style checker
