### ISSUE TITLE
Add travis ci

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#33]
Needs to be done after the PHPUNIT issue

**Comment by Tjoosten** [comment]
I can add it now. But it will get build status failed because the 3 internal server errors.

**Comment by ghermans** [comment]
@Tjoosten travis ci has been added

**Comment by Tjoosten** [comment]
The only thing i need is the public link so i can start write the travisCI config

**Comment by ghermans** [comment]
@Tjoosten  https://travis-ci.org/idevelopment/suitecrm_laravel
