### ISSUE TITLE
Left sidebar is not shown on mobile devices

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#34]
The left sidebar is not shown on mobile devices

![wp_ss_20151001_0001](https://cloud.githubusercontent.com/assets/1594411/10233454/ca5b577c-688e-11e5-8c08-ca6325d9047c.jpg)

**Comment by ghermans** [comment]
This needs to be fixed before we will use Sass

**Comment by Tjoosten** [comment]
Why we don't fix it in scss and comile it then to css?

**Comment by ghermans** [comment]
I agree

**Comment by Tjoosten** [comment]
Hehe

**Comment by ghermans** [comment]
will be fixed with #12

**Comment by ghermans** [comment]
* Left sidebar will be removed for mobile devices.
* Links from the sidebar will be integrated in the navbar menu.

**Comment by Tjoosten** [comment]
I there a issue for?

**Comment by ghermans** [comment]
@Tjoosten not for the current moment
