### ISSUE TITLE
Add timezone for users

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#38]
On the profile page the user should be able to set his timezone

**Comment by Tjoosten** [comment]
U planned to work with a database? If yes i can write the migration and seeder

**Comment by ghermans** [comment]
@Tjoosten yes, thanks for the upcoming work ;)

**Comment by Tjoosten** [comment]
Alright can we set this to 1.1.0?

**Comment by Tjoosten** [comment]
I need only a list that i can migrate

**Comment by Tjoosten** [comment]
this one? http://www.timeanddate.com/time/zones/ or the one from php?

**Comment by ghermans** [comment]
@Tjoosten  the one from php

**Comment by Tjoosten** [comment]
**Update:** Working on a method to write the db seeder

**Comment by ghermans** [comment]
Todo:

- [ ] Add select box on profile page.
