### ISSUE TITLE
add badges to readme

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#39]
**Badges** 

- [x] NodeJS dependencies
- [x] License 
- [x] TravisCi 
- [x] Gitter
- [x] Code coverage 
- [x] Semver versioning

**Comment by Tjoosten** [comment]
@ghermans for the NodeJS include the normal depencies or also the dev dependencies

**Comment by ghermans** [comment]
@Tjoosten any updates regarding this issue report?

**Comment by Tjoosten** [comment]
The following unchecked labels needed to be added

**Comment by Tjoosten** [comment]
**Note** TravisCi is implemented

**Comment by ghermans** [comment]
@Tjoosten  any updates regarding the nodejs?

**Comment by Tjoosten** [comment]
Fixed and closed
