### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#41]
Maybe we need a website where we promote this project? 

@ghermans feedback is welcome.

**Comment by ghermans** [comment]
Great idea, shall we use the Github pages or external site?

**Comment by Tjoosten** [comment]
github pages should be fine. But maybe we need to disqus the plan over skype?

**Comment by ghermans** [comment]
Repo for the website has been created, all discussions about the community website will be posted in that repo.

**Comment by Tjoosten** [comment]
Alright
