### ISSUE TITLE
Internal server error.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#42]
Internal server error on the url `/cases` 

<img width="538" alt="schermafbeelding 2015-10-04 om 04 02 38" src="https://cloud.githubusercontent.com/assets/5157609/10266083/dd65880a-6a4c-11e5-9336-0ed885014587.png">

**Update:** Same for `cases/read`

**Comment by ghermans** [comment]
As spoken on Skype, this file is not in use and is safe to delete

**Comment by ghermans** [comment]
File has been removed
