### ISSUE TITLE
Bring hyperlinks to the contribution file. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#45]

**Comment by ghermans** [comment]
@Tjoosten  any update for this enhancement?

**Comment by Tjoosten** [comment]
Yes i will bring it up tomorrow. With the documentation placement

**Comment by ghermans** [comment]
@Tjoosten can you close this issue when you push the commit?

**Comment by Tjoosten** [comment]
It is in the commit planned on Wednesday
