### ISSUE TITLE
Upgrade to laravel 5.1

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#47]
@ghermans milestone 1.1.0 of 2.0.0 your choice

**Comment by ghermans** [comment]
1.1.0 since it will be used for ACL #35

**Comment by Tjoosten** [comment]
Alright

**Comment by Tjoosten** [comment]
Are we migrated to 5.1?

**Comment by ghermans** [comment]
No

**Comment by ghermans** [comment]
Will reopen when we work on v2.0.0

**Comment by ghermans** [comment]
@Tjoosten the upgrade to Laravel 5.1 is done.
