### ISSUE TITLE
Add rest client 

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#5]
We should add nusoap to laravel because the current (joomla AOP) uses this to make the connection to SuiteCRM.

**Comment by Tjoosten** [comment]
Can we use the rest client in place of nusoap

**Comment by ghermans** [comment]
@Tjoosten

Found on http://support.sugarcrm.com/02_Documentation/04_Sugar_Developer/Sugar_Developer_Guide_6.5/02_Application_Framework/Web_Services/

REST examples: http://support.sugarcrm.com/02_Documentation/04_Sugar_Developer/Sugar_Developer_Guide_6.5/02_Application_Framework/Web_Services/Examples/REST/PHP/

Sugarcrm / suitecrm has 2 ways to build integrations for reading and writing data. Sugar provides Web Services APIs through the NuSOAP PHP implementation of the SOAP and REST protocol. SOAP (Simple Object Access Protocol) is used for making Remote Procedure Calls through the HTTP protocol by relaying messages in XML. The SugarSoap APIs, built on top of the NuSOAP PHP library, are included in the Sugar Community, Sugar Professional, Sugar Corporate, Sugar Enterprise, and Sugar Ultimate editions. REST (Representational State Transfer) is used for making method calls through HTTP protocol by sending and receiving messages in JSON/Serialize format. Framework supports the addition of multiple formats for REST. For example, you can add XML format to send and receive data.

**Comment by ghermans** [comment]
This issue is related to #2

**Comment by Tjoosten** [comment]
No Soap. Rest will be used

**Comment by ghermans** [comment]
To access the Suitecrm REST service you can use 

```
http://testplein.idevelopment.be/suitecrm/service/v4/rest.php
```

**Comment by Tjoosten** [comment]
?
