### ISSUE TITLE
Make a readthedocs portal.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#53]
Where we make a manual for developers and users.

**Articles:**

- [x] Usage of gulp. 
- [ ] Usage of phpcs. 
- [ ] Usage of phpunit. 
- [ ] Usage of scss-lint.
- [ ] Contribution guide. 
- [ ] Project info. 
- [x] Add license

**Comment by Tjoosten** [comment]
@ghermans any suggestions?

**Comment by Tjoosten** [comment]
License added

**Comment by ghermans** [comment]
@Tjoosten i guess the list is enough to start with.
