### ISSUE TITLE
Populate country list from db on profile page

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#54]
We should add a select box and populate this with all the countries.

**Comment by Tjoosten** [comment]
TODO: Create migration & seeder

**Comment by Tjoosten** [comment]
**Update: ** I'm working on the seeder.

**Comment by Tjoosten** [comment]
Fixed will be pushed on friday

**Comment by ghermans** [comment]
Reopened until push is done.

**Comment by ghermans** [comment]
TODO: 

- [ ] Populate the selectbox on the profile page
