### ISSUE TITLE
Remove rest controller and replace this with library

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#60]
The rest controller was just an example for using rest to make a connection to SuiteCRM.

**Comment by Tjoosten** [comment]
Is there a library?

**Comment by ghermans** [comment]
@Tjoosten no, we still need to create the library.

**Comment by ghermans** [comment]
The issue has been created for this #2

**Comment by Tjoosten** [comment]
Reopened and set the label wontfix
