### ISSUE TITLE
Add validation on forms

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#62]
We need to add some security validation on forms (required inputs etc)

**Comment by Tjoosten** [comment]
Maybe we can do this after the migration to L 5.1? Validation is easier to set in 5.1

**Comment by Tjoosten** [comment]
On what forms you want to set it?

**Comment by ghermans** [comment]
Forms that need validation

* My profile 
* Change password
* Create case

**Comment by Tjoosten** [comment]
All fields?
