### ISSUE TITLE
Kill psr-2 violations.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#63]
I did a quick scan on the code. And i think we need to improve the code quality. 
The are circ. 880 PSR-2 issues. 

@ghermans what u think should i?

**Comment by ghermans** [comment]
I created a new branch "unstable" this one will be used to check all the files before we do a release.

**Comment by ghermans** [comment]
@Tjoosten feel free to verify

**Comment by ghermans** [comment]
@Tjoosten thanks for the cooperation

**Comment by Tjoosten** [comment]
If you needed more help you can mail me at Topairy@gmail.com

2016-02-19 2:32 GMT+01:00 Glenn Hermans <notifications@github.com>:

**Comment by ghermans** [comment]
@Tjoosten i have added you on Gitter instead using mail :)
