### ISSUE TITLE
Typo in the website.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/suitecrm_laravel#67]
<img width="412" alt="schermafbeelding 2015-10-18 om 23 18 06" src="https://cloud.githubusercontent.com/assets/5157609/10566697/8cea4cf0-75ee-11e5-9062-b241ecfb718e.png">

Affects users that want to try the demo. 

need ***ASAP*** a fix. @ghermans

**Comment by ghermans** [comment]
fixed
