### ISSUE TITLE
Integrate phone prefix with the country iso codes

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#71]

**Comment by ghermans** [comment]
i don't think this will be added to v1.1.0 for now, will close this enhancement.

**Comment by Tjoosten** [comment]
a couple more needs to be done

**Comment by ghermans** [comment]
I will add the missing phone prefix.

**Comment by Tjoosten** [comment]
alright

**Comment by ghermans** [comment]
We need to check if all Phone prefix are completed.
In case all prefix are completed we can close this ticket.
