### ISSUE TITLE
User can not make connection to SuiteCRM

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#75]
This bug / question was reported on the SuiteCRM forum.

https://suitecrm.com/forum/developer-help/3817-advancedopenportal-with-laravel#24527

Do you have any installation docs created? I created the db, I edited the .env.example file then renamed to .env then i ran the php artisan migrate command, that worked, Now i assume i need to so some more configuration inside suitecrm so when i create a portal user it will add it to the db of your portal. I tried in the AOP setting for Joomla url to add www.domain.com/laravel/public but that didnt work?

I really like the look of your portal joomla has tooo much going on for me. Is it possible to add a feature that will store the users passwords under Suitecrm contacts by creating another field in contacts?

keep up the good work.

**Comment by ghermans** [comment]
@Tjoosten we really need to add the rest (guzzle) library asap

**Comment by Tjoosten** [comment]
give me the suiteCRM api reference about this plz

**Comment by ghermans** [comment]
http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Web_Services/

**Comment by ghermans** [comment]
Issue will be fixed when #5 is closed
