### ISSUE TITLE
Write SuiteCRM credentials to config file

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#80]
Todo

- [x] Create suitecrm config file
- [x] Create form for updating credentials 
- [ ] Update / write SuiteCRM credentials to config file.

**Comment by Tjoosten** [comment]
can u explain the last point plz?

**Comment by ghermans** [comment]
The last point is the action where we write the form to the config file.

**Comment by Tjoosten** [comment]
thought: what if we write the config values into the db. And parse them in the config file?

**Comment by ghermans** [comment]
@Tjoosten  why?

**Comment by Tjoosten** [comment]
so i can think maybe on some logic
