### ISSUE TITLE
[Clean install]  [PDOException]                                                                  SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 27 

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#83]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column   
  count doesn't match value count at row 27 (SQL: insert into `Countries` (`D  
  ial_nr`, `country`) values (+93, Afghanistan), (+355, Albania), (+213, Alge  
  ria), (+1-648, American Samoa), (+376, Andorra), (+244, Angola), (+1-264, A  
  nguilla), (+672, Antartica), (+1-268, Antigua and Barbuda), (+54, Argentina  
  ), (+374, Armenia), (+297, Aruba), (+61, Australia), (+43, Austria), (+994,  
   Azerbaijan), (+1-242, Bahamas), (+973, Bahrain), (+880, Bangladesh), (+1-2  
  46, Barbados), (+375, Belarus), (+32, Belguim), (+501, Belize), (+229, Beni  
  n), (+1-441, Bermuda), (+975, Bhutan), (+591, Bolivia), (Bonaire, Sint Eust  
  atius ans Saba), (+387, Bosnia and Herzegovina), (+267, Botswana), (Bouvet   
  Island), (+55, Brazil), (+246, British Indian Ocean Territory), (+673, Brun  
  ei), (+359, Bulgaria), (+266, Burkina Faso), (+257, Burundi), (+855, Cambod  
  ia), (+237, Cameroon), (+1, Canada), (+238, Cape Verde), (+1-345, Cayman Is  
  lands), (+236, Central African Republic), (+235, Chad), (+56, Chile), (+86,  
   China), (+61, Christmas Island), (+61, Cocos (Keeling) Islands), (+57, Col  
  ombia), (+269, Comoros), (+682, Cook islands), (+502, Costa Rica), (Cote de  
   azur), (+385, Croatia), (+53, Cuba), (+599, Curacao), (+357, Cyprus), (420  
  , Czech Republic), (+243, Democratic Republic of the congo.), (+45, Denmark  
  ), (253, Djibouti), (+1-767, Dominica), (+1-809, +1-829, +1-849, Dominican   
  Republic), (+593, Ecuador), (+20, Egypt), (+503, El Salvador), (+240, Equat  
  orial Guinea), (+291, Eritrea), (+372, Estonia), (+251, Ethiopia), (+500, F  
  alkland islands), (+298, Faroe Islands), (+679, Fiji), (+358, Finland), (+3  
  3, France), (French Guiana), (+689, French Polynesia), (French Southern Ter  
  ritory), (+241, Gabon), (+220, Gambia), (+995, Georgia), (+49, Germany), (+  
  233, Ghana), (+350, Gibraltar), (+30, Greece), (+299, Greenland), (+1-473,   
  Grenada), (Guadaloupe), (+1-671, Guam), (+502, Guatamala), (+44-1481, Guern  
  sey), (+224, Guinea), (+245, Guinea-Bissau), (+592, Guyana), (+509, Haiti),  
   (Heard Island and McDonals Island), (+504, Honduras), (+852, Hong Kong), (  
  +36, Hungary), (+354, Iceland), (+91, India), (+62, Indonesia), (+98, Iran)  
  , (+964, Iraq), (+353, Ireland), (+44-1624, Isle of Man), (972, Israel), (+  
  39, Italy), (+1-876, Jamaica), (+81, Japan), (+44-1534, Jersey), (+962, Jor  
  dan), (+7, Kazakhstan), (+254, Kenya), (+686, Kiribati), (+383, Kosovo), (+  
  965, Kuwait), (+996, Kyrgyzstan), (+856, Laos), (+371, Latvia), (+961, Leba  
  non), (+266, Lesotho), (+231, Liberia), (+218, Libya), (+423, Liechtenstein  
  ), (+370, Lithuania), (+352, Luxembourg), (+853, Macao), (+389, Macedonia),  
   (+261, Madagascar), (+265, Malawi), (+60, Malaysia), (+960, Maldives), (+2  
  23, Mali), (+356, Malta), (+692, Marshall Islands), (Martinique), (+222, Ma  
  uritinia), (`230`, Mauritius), (+262, Mayotte), (+52, Mexico), (+691, Micro  
  nesia), (+373, Moldava), (+377, Monaco), (+976, Mongolia), (+382, Montenegr  
  o), (+1-664, Montserrat), (+212, Morocco), (+258, Mozambique), (+95, Myanma  
  r (Burma)), (+264, Namibia), (+674, Nauru), (+977, Nepal), (+31, Netherland  
  s), (+687, New Caledonia), (+64, New Zealand), (+505, Nicaragua), (+227, Ni  
  ger), (+234, Nigeria), (+683, Niue), (Norfolk Island), (+850, North Korea),  
   (+1-670, Northern Mariana Islands), (+47, Norway), (+968, Oman), (+92, Pak  
  istan), (+680, Palau), (+970, Palestine), (+507, Panama), (+675, Papua New   
  Guinea), (+595, Paraguay), (+51, Peru), (+63, Phillipines), (+64, Pitcaim),  
   (+48, Poland), (+351, Portugal), (+1-787, +1939, Puerto Rico), (+974, Qata  
  r), (+262, Reunion), (+40, Romania), (+7, Russia), (+250, Rwanda), (+590, S  
  aint Barthelemy), (+290, Saint Helena), (+1-1869, Saint Kitts and Nevis), (  
  +1-759, Saint Lucia), (+590, Saint Martin), (+509, Saint Pierre and Miquelo  
  n), (+1-784, Saint Vincent and the Grenadines), (+685, Samoa), (+378, San M  
  arino), (+239, San Tome and Principe), (+966, Saudi Arabia), (+221, Senegal  
  ), (+381, Serbia), (+248, Seychelles), (+232, Sierra Leone), (+65, Singapor  
  e), (+1-721, Sint Maarten), (+421, Slovakia), (+386, Slovenia), (+677, Solo  
  mon Islands), (+252, Somalia), (+27, South Africa), (South Georgia and the   
  South Sandwich Islands), (+82, South Korea), (+34, Spain), (+94, Sri Lanka)  
  , (+249, Sudan), (+597, Suriname), (+47, Svalbard and Jan Mayen), (+268, Sw  
  aziland), (+46, Sweden), (+41, Switzerland), (+963, Syria), (+886, Taiwan),  
   (+992, Tajikistan), (+255, Tanzania), (+66, Thailand), (, Timor-Leste (Eas  
  t Timot)), (+228, Togo), (+690, Tokelau), (+676, Tonga), (+1-868, Trinidad   
  and Tobago), (+216, Tunesia), (+90, Turkey), (Turkmenistan), (Turks and Cai  
  cos Islands), (Tuvalu), (Uganda), (Ukraine), (United Arab Emirates), (Unite  
  d Kingdom), (United States), (United States Minor Outlying Islands), (Urugu  
  ay), (Uzbekistan), (Vanuatu), (Vatican City), (Venezuela), (Vietname), (Vir  
  igin Islands (British)), (Vigin Islands (US)), (Wallis and Futuna), (Wester  
  n Sahara), (Yemen), (Zambia), (Zimbabwe))

**Comment by Tjoosten** [comment]
working on a fix now

**Comment by Tjoosten** [comment]
reason for reopening?

**Comment by ghermans** [comment]
This was not closed ? is this fixed ?

**Comment by Tjoosten** [comment]
db seeder for countries is fixed and sorry my fault

**Comment by ghermans** [comment]
Thanks for the fix.
