### ISSUE TITLE
 codecov/project failed to check pull requests

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#90]
After the upgrade this morning the codecov checks are failing

**Comment by ghermans** [comment]
It looks like the webhook token for github is not valid anymore, @Tjoosten can you check this out?

**Comment by ghermans** [comment]
It looks like codecov is checking the master however it outputs 

" No diff could be generated. No reports for master found."

**Comment by Tjoosten** [comment]
i will check it tomorrow

**Comment by ghermans** [comment]
@tjoosten any update on this?

**Comment by Tjoosten** [comment]
I'm busy with it! But can't trace the error so far.
